name: Tagging

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Read version
        run: |
          VERSION=$(cat package.json | grep -P '"version":\s"(\d+\.\d+)"' | grep -oP '\d+\.\d+')
          echo "Version (package.json): $VERSION"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
      - name: Tag and Push
        run: |
          git config user.name "Stephan Arthold"
          git config user.email "stephan.arthold@aconio.net"
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            git tag $VERSION
            git push origin $VERSION
          fi
