name: Tagging

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "Stephan Arthold"
          git config user.email "stephan.arthold@aconio.net"

      - name: Determine the next tag version
        id: tag_version
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")

          latest_version=${latest_tag#v}
          IFS='.' read -r major minor patch <<< "$latest_version"
          new_tag="v$major.$minor.$((patch+1))"

      - name: Create and push tag
        env:
          TAG: ${{ env.new_tag }}
        run: |
          git tag "$TAG"
          git push origin "$TAG"
